### ISSUE TITLE
Child script?

### ISSUE THREAD

**Issue by danbars** [Lemick/open-iframe-resizer#4]
Hi,

Thanks for creating this open alternative.
Can you please shed some light on the child script? In the example I don't see that the child has any script. Does this work without it  somehow? Or does it work only because the parent and child have the same origin?

If a child script is needed, can you please show an example how it should be included? 

Thanks!

**Comment by Lemick** [comment]
Hi, thanks :)

Yes, if you talk about [this example](https://codesandbox.io/p/sandbox/open-iframe-resize-browser-m655zt), the child iframe does not need to load any script since the parent and the iframe share the same origin, thus the parent has full control other the iframe element.

There is an example of a cross-origin setup:
- [Parent page](https://codesandbox.io/p/sandbox/xj24pg?file=%2Findex.html)
- [Child page](https://codesandbox.io/p/sandbox/growing-iframe-msv4hr?file=%2Findex.html%3A12%2C13)

You always need to import the same script, as the script will automatically register the necessary listener if the current window is an iframe, I hope this is clear 👍

**Comment by laoneo** [comment]
Don't know how big the difference is, but from tree shaking perspective it would make sense to divide into child and parent code and provide an export for each one.
